---
- hosts: all
  gather_facts: no
  sudo: false
  tasks:
    - shell: sudo apt-get update
    - shell: sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
    - shell: cd
    - shell: git clone git://github.com/sstephenson/rbenv.git .rbenv
    - shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    - shell: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    - shell: git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    - shell: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
    - shell: source ~/.bashrc
    - shell: rbenv install -v 2.2.1
    - shell: rbenv global 2.2.1
    - shell: "echo gem: --no-document > ~/.gemrc"
    - shell: gem install bundler
